// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3so4f7McG9ysNUOJwpodJA9jkVSWlqLQ',
    appId: '1:105800259177:web:da98d301e1173b764974f8',
    messagingSenderId: '105800259177',
    projectId: 'flutter-iot-project-11d02',
    authDomain: 'flutter-iot-project-11d02.firebaseapp.com',
    storageBucket: 'flutter-iot-project-11d02.firebasestorage.app',
    measurementId: 'G-87DXSFD032',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-a6aGYCQpW5krLHh5OMiUN-arkVPKVOQ',
    appId: '1:105800259177:android:5195ee2032a610884974f8',
    messagingSenderId: '105800259177',
    projectId: 'flutter-iot-project-11d02',
    storageBucket: 'flutter-iot-project-11d02.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3so4f7McG9ysNUOJwpodJA9jkVSWlqLQ',
    appId: '1:105800259177:web:45a4fe7a24398c9e4974f8',
    messagingSenderId: '105800259177',
    projectId: 'flutter-iot-project-11d02',
    authDomain: 'flutter-iot-project-11d02.firebaseapp.com',
    storageBucket: 'flutter-iot-project-11d02.firebasestorage.app',
    measurementId: 'G-FR25J583ZG',
  );
}
